### ISSUE TITLE
Make new checkpoint_biggest

### ISSUE THREAD

**Issue by ksSoundAg** [isayev/ReLeaSE#26]
Hello,
I was wondering if you have the python code for how you created the checkpoint_biggest from the chembl file?  It also mentions loading multiple parameters in the abstract of the paper, do you have any implementation with more than one parameter?

Thank you,
Kevin

**Comment by ksSoundAg** [comment]
Hello,

I missed the updated implementation and saw the way to make a new model from the chembl file in the python notebook.  I am still wondering if you have any suggestions on the implementation of multiple parameters.

Thank you for your time,
Kevin

**Comment by ksSoundAg** [comment]
I have been trying to run the commented out code in the python notebook to produce a new checkpoint_biggest using the provided Chembl file, but get the following error every time I try to run the script each time at different generation numbers. : 
Training in progress...:   0%|                                                                                                  | 99/1500000 [00:09<37:07:28, 11.22it/s][0m 9s (100 0%) 2.6547]
<V+778ycV<CnatHnsO(CEN/Hu]Tg6\LpdWX<uFI9YDfE9bf3pMF/GE4mI[]9]H59I
Tu=PDVP5]6
Z>

Training in progress...:   0%|                                                                                                 | 198/1500000 [00:18<37:05:32, 11.23it/s][0m 18s (200 0%) 1.4145]
Traceback (most recent call last):
  File "multi.new.runReleaseask.190404.newgenerator.py", line 119, in <module>
    losses = my_generator.fit(gen_data, 1500000)
  File "/home/ubuntu/Release2/stackRNN.py", line 459, in fit
    predict_len=100), '\n')
  File "/home/ubuntu/Release2/stackRNN.py", line 391, in evaluate
    output, hidden, stack = self.forward(inp, hidden, stack)
  File "/home/ubuntu/Release2/stackRNN.py", line 215, in forward
    inp = torch.cat((inp, stack_top), dim=2)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 2. Got 1 and 2 in dimension 1 at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/generic/THCTensorMath.cu:87
Exception ignored in: <bound method tqdm.__del__ of Training in progress...:   0%|                                                                                                 | 198/1500000 [00:18<37:05:32, 11.23it/s]>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 889, in __del__
    self.close()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1095, in close
    self._decr_instances(self)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 454, in _decr_instances
    cls.monitor.exit()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 1053, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
